#pragma once
#include "Player.h"
#include "CollTestBox.h"
#include "Background.h"
#include "TileSheet.h"
#include "Button.h"
#include "ScreenFillSprite.h"
#include "BoxBoy.h"
#include "BoxBot.h"
#include "Tracks.h"
#include "DragonBoy.h"
#include "Cookie.h"
#include "DBoyProjectile.h"
#include "RobertsFriends.h"
#include "Cookie.h"
#include "Marble.h"
<<<<<<< HEAD
#include "AsianPaperBoy.h"
=======
#include "BigBoxBoy.h"
>>>>>>> e99138d28c932d78aa61d367f29f72751b8c18d2
